// This file will be auto-generated by the pull-contracts script
// For now, we'll use placeholder types

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string;
          name: string;
          slug: string | null;
          logo_url: string | null;
          primary_color: string;
          plan_key: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug?: string | null;
          logo_url?: string | null;
          primary_color?: string;
          plan_key?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_tenants: {
        Row: {
          id: string;
          user_id: string;
          tenant_id: string;
          role: 'owner' | 'admin' | 'member' | 'viewer';
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          tenant_id: string;
          role?: 'owner' | 'admin' | 'member' | 'viewer';
          created_at?: string;
        };
      };
      team_members: {
        Row: {
          id: string;
          tenant_id: string;
          user_id: string;
          display_name: string | null;
          role: 'owner' | 'admin' | 'member';
          permissions: any;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          user_id: string;
          display_name?: string | null;
          role?: 'owner' | 'admin' | 'member';
          permissions?: any;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      campaigns: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          created_at: string;
        };
      };
      contacts: {
        Row: {
          id: string;
          tenant_id: string;
          email: string;
          created_at: string;
        };
      };
      locations: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          address: string;
          city: string | null;
          state: string | null;
          zip_code: string | null;
          country: string;
          latitude: number | null;
          longitude: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          name: string;
          address: string;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          country?: string;
          latitude?: number | null;
          longitude?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      verticals: {
        Row: {
          id: string;
          key: string;
          name: string;
          description: string | null;
          icon: string | null;
          language_config: any;
          created_at: string;
        };
      };
      tenant_verticals: {
        Row: {
          id: string;
          tenant_id: string;
          vertical_key: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          vertical_key: string;
          created_at?: string;
        };
      };
    };
  };
}
