// This file will be auto-generated by the pull-contracts script
// For now, we'll use placeholder types

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          created_at: string;
        };
      };
      tenants: {
        Row: {
          id: string;
          name: string;
          created_at: string;
        };
      };
      campaigns: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          created_at: string;
        };
      };
      contacts: {
        Row: {
          id: string;
          tenant_id: string;
          email: string;
          created_at: string;
        };
      };
      locations: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          created_at: string;
        };
      };
    };
  };
}
